version: '3'
services:
  memcached:
    container_name: some-memcached
    image: bitnami/memcached:latest
    ports:
      - '127.0.0.1:11211:11211'
  mysql:
    image: mysql:5.6.27    
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb/dump.sql:/docker-entrypoint-initdb.d/dump.sql  
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: codecamp
      TZ: Asia/Kolkata

volumes:
  mysqldata:
    driver: local